name: Admin - Bump Minor Version
on:
  pull_request:
    types: [closed]
    branches:
      - main
      - release/*/lts

jobs:
  bump:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump Version
        uses: kungfu-trader/action-bump-version@v3
        with:
          token: ${{ secrets.KUNGFU_GITHUB_TOKEN }}
